[build]
  command = "chmod +x ./build.sh && ./build.sh"
  functions = "functions"

[build.environment]
  GO_IMPORT_PATH = "github.com/laof/redirect"
  GO111MODULE = "on"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/gateway/:splat"
  status = 200
