[build]
	command = "make build"
	functions = "./functions"
[build.environment]
	GO_IMPORT_PATH = "github.com/laof/redirect"
	GOBIN = "/opt/build/repo/functions"


[[redirects]]
  from = "/*"
  to = "/.netlify/functions/go"
  status = 200